### ISSUE TITLE
invoicedQuantity not working

### ISSUE THREAD

**Issue by JiriSch** [adawolfa/isdoc#1]
Hello, thank you for this class, I found Quantity is not working:

```
$invoicedQuantity = new Adawolfa\ISDOC\Schema\Invoice\Quantity();
$invoicedQuantity->setUnitCode('ks');
$invoicedQuantity->setContent('99');
$InvoiceLine->setInvoicedQuantity($invoicedQuantity);
```

Generates:
`<InvoicedQuantity unitCode="ks"/>`

UnitCode presents, but not quantity.

Thanks for advice/help.

**Comment by adawolfa** [comment]
Hello, thanks for reporting. This should be fixed in `1.0.5`.

Beware, I've been using this pretty much only for reading the invoices, so it's far from being battle-tested when it comes to writing them (which is also why the decorated API is rather basic and there's no support for the enveloped signature that nobody seems to care about).
